# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x06\x43lient\x1a\x19google/protobuf/any.proto\"t\n\tSubscribe\x12(\n\x06stream\x18\x01 \x03(\x0b\x32\x18.Client.Subscribe.Stream\x1a=\n\x06Stream\x12\x0e\n\x06stream\x18\x01 \x01(\t\x12\x11\n\tstartTime\x18\x02 \x01(\x03\x12\x10\n\x08startSeq\x18\x03 \x01(\x04\"\x1d\n\x0bUnsubscribe\x12\x0e\n\x06stream\x18\x01 \x03(\t\"{\n\x07Request\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x11\n\trequestId\x18\x02 \x01(\x03\x12$\n\tsubscribe\x18\x03 \x01(\x0b\x32\x11.Client.Subscribe\x12(\n\x0bunsubscribe\x18\x04 \x01(\x0b\x32\x13.Client.Unsubscribe\"B\n\x0cSubscription\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.Client.Status\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\"D\n\x0eUnsubscription\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.Client.Status\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\"y\n\x08Response\x12\x11\n\trequestId\x18\x01 \x01(\x03\x12*\n\x0csubscription\x18\x02 \x01(\x0b\x32\x14.Client.Subscription\x12.\n\x0eunsubscription\x18\x03 \x01(\x0b\x32\x16.Client.Unsubscription\"R\n\rStreamMessage\x12\x0c\n\x04subs\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12&\n\x08messages\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any*G\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0cSERVER_ERROR\x10\x01\x12\x11\n\rACCESS_DENIED\x10\x02\x12\x10\n\x0cNOT_ENTITLED\x10\x03\x62\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
OK = 0
SERVER_ERROR = 1
ACCESS_DENIED = 2
NOT_ENTITLED = 3


_SUBSCRIBE = DESCRIPTOR.message_types_by_name['Subscribe']
_SUBSCRIBE_STREAM = _SUBSCRIBE.nested_types_by_name['Stream']
_UNSUBSCRIBE = DESCRIPTOR.message_types_by_name['Unsubscribe']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_SUBSCRIPTION = DESCRIPTOR.message_types_by_name['Subscription']
_UNSUBSCRIPTION = DESCRIPTOR.message_types_by_name['Unsubscription']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_STREAMMESSAGE = DESCRIPTOR.message_types_by_name['StreamMessage']
Subscribe = _reflection.GeneratedProtocolMessageType('Subscribe', (_message.Message,), {

  'Stream' : _reflection.GeneratedProtocolMessageType('Stream', (_message.Message,), {
    'DESCRIPTOR' : _SUBSCRIBE_STREAM,
    '__module__' : 'client_pb2'
    # @@protoc_insertion_point(class_scope:Client.Subscribe.Stream)
    })
  ,
  'DESCRIPTOR' : _SUBSCRIBE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Client.Subscribe)
  })
_sym_db.RegisterMessage(Subscribe)
_sym_db.RegisterMessage(Subscribe.Stream)

Unsubscribe = _reflection.GeneratedProtocolMessageType('Unsubscribe', (_message.Message,), {
  'DESCRIPTOR' : _UNSUBSCRIBE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Client.Unsubscribe)
  })
_sym_db.RegisterMessage(Unsubscribe)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Client.Request)
  })
_sym_db.RegisterMessage(Request)

Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTION,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Client.Subscription)
  })
_sym_db.RegisterMessage(Subscription)

Unsubscription = _reflection.GeneratedProtocolMessageType('Unsubscription', (_message.Message,), {
  'DESCRIPTOR' : _UNSUBSCRIPTION,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Client.Unsubscription)
  })
_sym_db.RegisterMessage(Unsubscription)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Client.Response)
  })
_sym_db.RegisterMessage(Response)

StreamMessage = _reflection.GeneratedProtocolMessageType('StreamMessage', (_message.Message,), {
  'DESCRIPTOR' : _STREAMMESSAGE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:Client.StreamMessage)
  })
_sym_db.RegisterMessage(StreamMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=670
  _STATUS._serialized_end=741
  _SUBSCRIBE._serialized_start=51
  _SUBSCRIBE._serialized_end=167
  _SUBSCRIBE_STREAM._serialized_start=106
  _SUBSCRIBE_STREAM._serialized_end=167
  _UNSUBSCRIBE._serialized_start=169
  _UNSUBSCRIBE._serialized_end=198
  _REQUEST._serialized_start=200
  _REQUEST._serialized_end=323
  _SUBSCRIPTION._serialized_start=325
  _SUBSCRIPTION._serialized_end=391
  _UNSUBSCRIPTION._serialized_start=393
  _UNSUBSCRIPTION._serialized_end=461
  _RESPONSE._serialized_start=463
  _RESPONSE._serialized_end=584
  _STREAMMESSAGE._serialized_start=586
  _STREAMMESSAGE._serialized_end=668
# @@protoc_insertion_point(module_scope)
