# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: md_eex_analytics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16md_eex_analytics.proto\x12\reex.analytics\"\xf3\x01\n\x05Index\x12\r\n\x05\x43mdty\x18\x01 \x01(\t\x12\x0c\n\x04\x41rea\x18\x02 \x01(\t\x12\r\n\x05Index\x18\x03 \x01(\t\x12\x10\n\x08LongName\x18\x04 \x01(\t\x12\x13\n\x0b\x44\x65liveryDay\x18\x05 \x01(\t\x12\r\n\x05Start\x18\x06 \x01(\x03\x12\x0b\n\x03\x45nd\x18\x07 \x01(\x03\x12\x0b\n\x03UOM\x18\x08 \x01(\t\x12\x10\n\x08\x43urrency\x18\t \x01(\t\x12\x0f\n\x07TrdDate\x18\n \x01(\t\x12\n\n\x02Px\x18\x0b \x01(\x01\x12\x0b\n\x03Vol\x18\x0c \x01(\x01\x12\x0f\n\x07\x42OMcode\x18\r \x01(\t\x12\x15\n\rSecurityAltID\x18\x0e \x01(\x03\x12\n\n\x02Tm\x18\x63 \x01(\x03\x42(Z&dev/ccs-service/dbag/gen/eex.analyticsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'md_eex_analytics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z&dev/ccs-service/dbag/gen/eex.analytics'
  _INDEX._serialized_start=42
  _INDEX._serialized_end=285
# @@protoc_insertion_point(module_scope)
